### ISSUE TITLE
Completion order for output

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-output#115]
Currently data for completions are stored in the Well struct of opm/output/data/Wells.hpp as

``` C++
std::map< Completion::active_index, Completion > completions;
```

This is problematic because order of completions is lost upon output (replaced with sorted-by-active-index). When restoring the original state the ordering should be the same as when writing.
The simplest solution is replacing the map with a vector. An alternative could be building a mapping from active cell index to local completion position on the simulator side, but I think that is a more complicated and therefore worse solution.

**Comment by jokva** [comment]
https://github.com/OPM/opm-output/pull/116
