### ISSUE TITLE
Exception when "SGAS" is not in Solution

### ISSUE THREAD

**Issue by anrdnet** [OPM/opm-output#119]
When running a two-phase oil-water case, i get an uncaught exception from [map::at](https://github.com/OPM/opm-output/blob/67838b1b8a727bdc54a58ab87fc1c63422c5f546/opm/output/data/Solution.cpp#L40) when "SGAS" is requested [here](https://github.com/OPM/opm-output/blob/67838b1b8a727bdc54a58ab87fc1c63422c5f546/opm/output/eclipse/EclipseWriter.cpp#L352).

**Comment by joakim-hove** [comment]
Should be fixed with: #120

**Comment by anrdnet** [comment]
Seems to work.
