### ISSUE TITLE
WGOR unit is not properly handled for FIELD. 

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-output#146]
For example, for SPE1CASE2, which is using FIELD unit system, the output from OPM is 177 or 178 times of the output from Eclipse, which is approximately the ratio of the unit Mscf and stb. 

The WOPR under FIELD unit is `Mscf/stb`. 

I am not sure how the unit is handled in the summary part, while for this case, something need to be changed.

**Comment by jokva** [comment]
I'll have a look at this on Monday, but it can really only be one of two errors so it shouldn't be too difficult to fix. Thanks for the report!

**Comment by GitPaean** [comment]
Thanks. Have a nice weekend.

**Comment by jokva** [comment]
@GitPaean Could you please apply https://github.com/OPM/opm-parser/pull/991 and give it a spin?

**Comment by GitPaean** [comment]
fixed with PR OPM/opm-parser#991  . closing now.
