### ISSUE TITLE
Does the restart output supports the polymer related now?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-output#149]
I tried to put `POLYMER` under `RTRST` or `RTSCHED`, while I could not find any polymer related output in the UNRST file. 

Before I investigate more, I would like to have some ideas on whether we have this kind of support yet. 

Thanks.

**Comment by jokva** [comment]
For restart? Not at all.

**Comment by joakim-hove** [comment]
The general from@jokva is of course correct. However to *visualise* polymerstate is possible using the same approach as used for e.g. relperm.

Inspired by this query I have thought over the fact that writing and reading restart files is quite unsymmetric, personally I feel the write implementation is best. Maybe we should implement the read in the same way, then calling scope will just get a <string,double> map of values, and extract what it wants - without any special treatment of e.g `PRESSURE` and `SWAT`.
That way way @GitPaens question would become irrelevant.

**Comment by jokva** [comment]
I think that's a good idea and even proposed before. It's probably a nontrivial amount of work, but I think feasible.

**Comment by GitPaean** [comment]
I am not sure if I am following everything correctly. What I was trying to do is to visualize some polymer concentration from the flow-polymer simulation, either with ResInsight or MRST. I did not find anything related to polymer in the UNRST file.  It will be good for practical use if we have a flexible functionality that we can customize the variables we want to output to restart file for use of other purpose. 

Thanks for the answering and I am closing the issue now.

**Comment by joakim-hove** [comment]
Ok - but I actually think you should (at least) talk to your colleague Andre, if we are lucky the output part is actually ready.
