### ISSUE TITLE
FPR unit conversion bug? 

### ISSUE THREAD

**Issue by totto82** [OPM/opm-output#154]
FPR is off by a factor approx 1 bar. The case uses METRIC units.

**Comment by bska** [comment]
> FPR is off by a factor approx 1 bar.

How close is that approximation?  Is it more like 1.01325 bar (= 1 atmosphere)?

**Comment by atgeirr** [comment]
Which simulator and case?

**Comment by joakim-hove** [comment]
A bit more details please?

**Comment by joakim-hove** [comment]
Please come back with more details if this is for real - or close the case.

**Comment by totto82** [comment]
Sorry, I forgot about this one. There is still significant differences between Ecl and OPM on FPR values. For Model 2 realization 0 the difference is between 10 - 15 bar.

**Comment by joakim-hove** [comment]
> There is still significant differences between Ecl and OPM on FPR values. For Model 2 realization 0 the difference is between 10 - 15 bar.

Hmmm - I don't really understand; initially I had the impression this was a bug in the output layer, but now I get the impression that the error is in the *values* being outputted? In the latter case I would say the bug was in the simulator?

**Comment by totto82** [comment]
> Hmmm - I don't really understand; initially I had the impression this was a bug in the output layer, but now I get the impression that the error is in the values being outputted?

I also thought this was just a conversion bug. I don't have time to look deeper into this now. Do you want me to close this issue? And reopen it here or in opm-simulator when I have time to investigate this more.

**Comment by atgeirr** [comment]
> And reopen it here or in opm-simulator when I have time to investigate this more.

That seems reasonable. Assuming flow_ebos is the sim in question?

**Comment by joakim-hove** [comment]
I close this now. Reopen when/if appropriate.
