### ISSUE TITLE
where to MPI?

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-output#157]
maybe this is already implemented, if yes please let me know: It seems like opm-output assumes a global (i.e., non-distributed) view on the grid, i.e., the calling code needs to deal with collecting all data to the rank which writes the output etc. since this is IMO quite clumsy for downstream code, the question arises if there are plans for `opm-output` to become MPI aware in the near future?

**Comment by joakim-hove** [comment]
> It seems like opm-output assumes a global (i.e., non-distributed) view on the grid, i.e., the calling code needs to deal with collecting all data to the rank which writes the output etc

Yes - that is correct.

> . since this is IMO quite clumsy for downstream code, the question arises if there are plans for opm-output to become MPI aware in the near future?

There are no imminent plans to make opm-output MPI aware, and personally I think that is the way it should be. Observe that the (Eclipse) file formats are manifest serial.

**Comment by andlaus** [comment]
> There are no imminent plans to make opm-output MPI aware, and personally I think that is the way it should be. Observe that the (Eclipse) file formats are manifest serial.

sure. I'm just wondering if that whole "collect-the-data-on-rank-0" jazz is not better done within opm-output instead of within the simulator...

**Comment by atgeirr** [comment]
> sure. I'm just wondering if that whole "collect-the-data-on-rank-0" jazz is not better done within opm-output instead of within the simulator...

Taking as a given that we cannot avoid this due to the serial-ness of the I/O formats, I think it is *very good* to say that all the opm-output stuff is serial. This is because that clearly divides responsibility, clearly stating where you are allowed to "think serial" (opm-output) and where you are not.

**Comment by andlaus** [comment]
ok, seems like I've got some non-trivial work to do in `SimulatorFullyImplicitBlackoilOutputEbos.[ch]pp`

**Comment by blattms** [comment]
Maybe my memory is wrong, but didn't I tell you in one our hangouts
that parallel output is *my* next task? Or maybe I said "I have to fix
it" and meant that I am working on it. Mybe we should split up the
bugs found on Friday via private mail?

**Comment by andlaus** [comment]
Seems like we have a volunteer to do the work ;)

Seriously, I'm more than happy to concede this to you. As I understood this, we talked about that the output code currently expects a very weird mix of distributed and non-distributed data so I thought I'd have a look to find the crap which was my fault and fix it if possible. Honestly I was a bit surprised that *all* of this mess is caused by the simulator side, but I suppose I'll shut up on this issue from now on...

**Comment by jokva** [comment]
opm-output expects already serialised, non-distributed, non-parallel data (in the eclipse case, and one of the large reasons for as why output takes its argument *by value*, so that when the snapshot of state is frozen the simulator can keep going and be sure that nothing will be corrupted), but I think the simulator-only output features (VTK maybe?) can do things in parallel.

**Comment by andlaus** [comment]
> one of the large reasons for as why output takes its argument by value, so that when the snapshot of state is frozen

probably using by-value semantics is not necessary because the downstream code has to take care of memory management anyway (collecting everything on the output rank, etc.). I suppose that some form of lifecycle management (`std::shared_ptr`?) would be good, though.

> but I think the simulator-only output features (VTK maybe?) can do things in parallel.

yes, VTK is much easier to handle in this respect.

**Comment by blattms** [comment]
@andlaus You might need to be a bit more precise. What  you referred to (mixing of distributed and global stuff) in your last comment is not in the headers  SimulatorFullyImplicitBlackoilOutputEbos.[ch]pp that you mentioned in your previous comment. I just like to avoid duplicate work.

**Comment by andlaus** [comment]
> You might need to be a bit more precise. 

as far as I currently understand this, `BlackoilOutputWriterEbos::restore()`, `BlackoilOutputWriterEbos::initFromRestartFile()` and the constructor of that class expect a non-distributed grid and data, while the `write*()` methods expect a distributed one?

> I just like to avoid duplicate work.

me too, that's why I did not do any work yet ;)
