### ISSUE TITLE
NUMRES value inside the EGRID File

### ISSUE THREAD

**Issue by EnricoScantamburlo** [OPM/opm-output#196]
I was trying to visualize the data output by OPM with our own 3D visualizer, but it turned out it cannot because OPM does not write the NUMRES property inside the EGRID file. It should be 1 by default.

**Comment by joakim-hove** [comment]
Hello - the final writing of the EGRID files is handled by the libecl library. Hopefully this: https://github.com/Statoil/libecl/pull/125 should fix your issue.
