### ISSUE TITLE
Repo Link Not Found

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-output#260]
Repo link not found
http://www.opm-project.org/packages/current/redhat/6/opm.repo
404 error

**Comment by akva2** [comment]
where do you find that link? it's supposed to be https://opm-project.org/package/opm.repo

**Comment by OPMUSER** [comment]
I just spent 15 minutes looking for it it but I cannot find it now. If I come across it again I'll re-post.

Sorry for the noise.
