### ISSUE TITLE
Compile failure for current master

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-output#28]
I get the following compile error (and so does Travis):

```
/Users/atgeirr/opm-build-debug/opm-output/opm/output/eclipse/Summary.cpp:664:21: error: reference to 'conversions' is ambiguous
    using namespace conversions;
                    ^
/Users/atgeirr/opm-build-debug/opm-parser/opm/parser/eclipse/Units/ConversionFactors.hpp:240:11: note: candidate found by name lookup is 'Opm::conversions'
namespace conversions {
          ^
/Users/atgeirr/opm-build-debug/opm-output/opm/output/eclipse/Summary.cpp:62:11: note: candidate found by name lookup is 'Opm::(anonymous namespace)::conversions'
namespace conversions {
          ^
/Users/atgeirr/opm-build-debug/opm-output/opm/output/eclipse/Summary.cpp:667:51: error: use of undeclared identifier 'metric'
        case UnitSystem::UNIT_TYPE_METRIC: return metric;
                                                  ^
/Users/atgeirr/opm-build-debug/opm-output/opm/output/eclipse/Summary.cpp:668:50: error: use of undeclared identifier 'field'
        case UnitSystem::UNIT_TYPE_FIELD: return field;
                                                 ^
/Users/atgeirr/opm-build-debug/opm-output/opm/output/eclipse/Summary.cpp:669:25: error: use of undeclared identifier 'metric'
        default: return metric;
```

It should perhaps be simple to fix, but I cannot quite figure out how to refer to an anonymous namespace nested inside (!) the Opm namespace. I propose either to drop the anonymous namespace, move it to the outer scope (it's a cpp file so no problem) or use the name "details".

I don't think I know what is supposed to happen when nesting anonymous namespaces, and my first rule of C++ is that if I don't understand it it is bad...

**Comment by GitPaean** [comment]
I saw this too and just verified it by recompiling for another time.

**Comment by jokva** [comment]
Right. This **has** been fixed in my tree, but has yet to see master as refactoring opm-output is a lot of work.

I can push out a fix of just this feature so that master works nicely again if desired. If impatient, you can locally remove the Summary file contents as they're not enabled yet.

**Comment by alfbr** [comment]
Please provide the fix, we should aim to have master building at all times.

**Comment by jokva** [comment]
@atgeirr You can refer to things inside the anon namespace in the same file the same way you always do, and within a namespace it's contained to that file **and** that namespace. Anyway, this comes from conflicts with the same functionality implemented in parser (where it will live) and is fixed in https://github.com/OPM/opm-output/pull/29

**Comment by atgeirr** [comment]
Fixed, closing.
