### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-output#34]
The following line (and many similar ones) fails (Summary.cpp line 252):

```
case WT::wat: return units.from_si( units.measure::liquid_surface_rate, p.WaterRate );
```

The error message is

```
/Users/atgeirr/opm-build-debug/opm-output/opm/output/eclipse/Summary.cpp:252:60: error: 'Opm::UnitSystem::measure::liquid_surface_rate' is not a member of class 'const Opm::UnitSystem'
        case WT::wat: return units.from_si( units.measure::liquid_surface_rate, p.WaterRate );
                                                  ~~~~~~~~~^
```

I have not tried to solve the problem yet. This also breaks on Travis, yet still slipped through the safety net. I do not know if that's worth investigating though (perhaps a compiler issue?.

**Comment by jokva** [comment]
When did you pull last? A merge in parser was applied before the merge in output was ready, but it has been applied now. Do you have a fresh checkout? Of parser too, obviously, as it's defined there.

**Comment by pgdr** [comment]
Everything compiles here, and all tests are green.  I think this was fixed by #33 (which OPM/opm-parser#814 co-depended on).  Travis was also green before merging this.

**Comment by atgeirr** [comment]
I have a fresh checkout and everything identical to the upstream master. Will look at it.

**Comment by pgdr** [comment]
[`Opm::UnitSystem::measure::liquid_surface_rate`](https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/Units/UnitSystem.hpp#L51)

**Comment by joakim-hove** [comment]
This seems stale.

**Comment by atgeirr** [comment]
Yes it has been fixed. However the same issue showed up the other day (and was fixed again), so perhaps we should keep it around :-)
