### ISSUE TITLE
Summary output not respecting output_dir

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-output#45]
It seems that the output directory parameter is no longer used by the summary output facilities, and that summary files are always written to the current directory. Restart files are written to the correct dir however.

**Comment by jokva** [comment]
That's right. Summary still gets its configuration from the Deck, and ignores applications currently.

It's in the pipeline, along with plenty other changes to the summary subsystem.

**Comment by atgeirr** [comment]
Can I ask to increase the priority of this issue? It is very annoying when testing variants against each other, and it is very easy to mess up and make wrong comparisons.

**Comment by jokva** [comment]
It's pipelined. This will be more-or-less instantly resolved once IOConfig is properly independent and trivially copyable. Can't guarantee, but likely to happen some time this week.

**Comment by jokva** [comment]
https://github.com/OPM/opm-output/pull/52 will fix the immediate issue, but the proper fix is, as previously mentioned, slightly more work.

**Comment by atgeirr** [comment]
> It's pipelined

Great!

> #52 will fix the immediate issue

I'll test it.

**Comment by atgeirr** [comment]
Tested successfully, thanks!

**Comment by joakim-hove** [comment]
This should  be fixed with: https://github.com/OPM/opm-output/pull/52 - closing.
