### ISSUE TITLE
Summary output seemingly doubled?

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-output#47]
(sorry, accidentally hit enter)

When processing the summary output with the plotwells.sh utility from opm-data, I get all well figures twice. I do not know if it is a bug in the script that has been exposed by minor changes to output, or if the output is wrong.

**Comment by atgeirr** [comment]
I found out what was causing it: the script filters on the string WBHP, which now matches both the WBHP fields as well as the new WBHPH field. I guess that means it's the script that needs fixing. What is the WBHPH field anyway?

**Comment by jokva** [comment]
**W**ell **B**ottom **H**ole **P**ressure (**H**istory).

**Comment by atgeirr** [comment]
It seems to contain only zeros in my output. Do we eventually need to distinguish these (I hope not...)?

**Comment by jokva** [comment]
They're not supported (yet) and I'm unsure if Eclipse supports it properly, or if it's ever used. I don't think it's information available in the `EclipseState` yet either.

**Comment by atgeirr** [comment]
I'll push a fix for opm-data.
