### ISSUE TITLE
about the summary output

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-output#57]
Now, if we specify one record twice, we will get two same output in the summary file. 

For example, if we put

```
WGPR
   'PROD01'
/ 

WGPR
   'PROD01'
/ 
```

or We put 

```
WGPR
   'PROD01'
/ 

ALL
```

in the SUMMARY section, we will have two same `WGPR` output for well `PROD01`. I think there are some other occasions can trigger repeated output in the summary file, while I did not try. 

I am wondering if it is possible to remove the repeated output. I do not think it is a big problem, while better to have.

**Comment by jokva** [comment]
Nice catch. Yes, we can implement a unique-like function over summary entries, but no such support exists as of now.

**Comment by jokva** [comment]
@GitPaean Can you try out https://github.com/OPM/opm-parser/pull/869 and see if it works alright for you?
