### ISSUE TITLE
Open/shut well status for wells

### ISSUE THREAD

**Issue by jokva** [OPM/opm-output#58]
https://github.com/OPM/opm-simulators/pull/749#discussion_r69376844

>  As I see it the Right™ way to do this is that the simulator initialized/assigns the data:Wells structures correctly with open/shut status of wells and connections, and then that stumbles out to disk.

Great idea and put into TODO as a missing feature.

**Comment by atgeirr** [comment]
I take it that means: for now we cannot tell the data::Wells a well is shut, and therefore should use 0 rates (and I guess a dummy 0 bhp) for such wells?

**Comment by joakim-hove** [comment]
I don't know but I would strongly prefer to avoid dummy values, open a PR on data::well instead

**Comment by jokva** [comment]
For now we can't, but dummy values is a bad solution. `data::Wells` is there to easily and rather self-documenting exchange this kind of information between the simulator and the outside world. We'll add a member.

**Comment by atgeirr** [comment]
I'd rather you guys add that member, because you'd know where else in the output system it would/should come into play better than me. We'll connect it on the simulator end, then.

**Comment by jokva** [comment]
Fixed in https://github.com/OPM/opm-output/commit/970777a384fd809f03f04c5b108072e09c7f3331
