### ISSUE TITLE
No units from summary file when running flow

### ISSUE THREAD

**Issue by kristfho** [OPM/opm-output#60]
When running flow there are no units included in the summary files. I have tested on the cases `SPE9_CP`, `SPE1CASE1,` `SPE3CASE1` and `SPE3CASE2`

When printing the units for each well with my compareSummary binary this is some of the output when using the `opm-simulation-reference` for `SPE1CASE1`. 

`~/opm-output/build/bin/compareSummary ~/opm-data/spe1/opm-simulation-reference/SPE1CASE1` 

```
WBHP:INJ unit: PSIA
WBHP:PROD unit: PSIA
WGIR:INJ unit: MSCF/DAY
WGIR:PROD unit: MSCF/DAY
...etc.
```

When using the new summary files: 
`~/opm-output/build/bin/compareSummary ~/spe1/SPE1CASE1`

```
WBHP:INJ unit:
WBHP:PROD unit:
WGIR:INJ unit:
WGIR:PROD unit:
... etc.
```

The tendency for the four files I tested is that the units are included in the opm-simulation-reference and not in the new summary files created by flow. Is this intentional?

**Comment by joakim-hove** [comment]
Flow does not yet print units - it is on the todo list.
