### ISSUE TITLE
Shouldn't <MODEL>.PRT files be written to output_dir, too?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-output#86]
I just did a run with a model and output_dir set. Judging from the file modification time, <MODEL>.PRT got written to the current directory and not the ouput_dir. Is that a feature?

**Comment by blattms** [comment]
I correct myself. Two such files are written, one in the current directory and one in output_dir. Unfortunately, they differ in size.

**Comment by atgeirr** [comment]
> Is that a feature?

No, while it should default to current dir, it should be overridable. To me, it looks like you found a bug. Does this happen in parallell only?

**Comment by atgeirr** [comment]
Another thing or two:
- I think that opm-output may not be the correct place to discuss this, as the PRT files are part of the logging feature set.
- Assuming this is caused by parallel runs: I have long thought that parts of the logging was essentially broken in parallel, but have not had the time to investigate in detail how, it would be interesting to know what is actually in the two different files...

**Comment by GitPaean** [comment]
From my side, it only happens when running in parallel with 2 mpi processes (did not try more cores).

**Comment by blattms** [comment]
Yes it happens in parallel. Might even be fixed by OPM/opm-simulators#770. Closing.

**Comment by blattms** [comment]
It happens always:

```
mblatt@boromir:~/src/dune/opm/opm-data/spe1$ ls -l *PRT
-rw-r--r-- 1 mblatt mblatt 1381 Jul 27 13:38 SPE1CASE1.PRT
mblatt@boromir:~/src/dune/opm/opm-data/spe1$ ../../opm-simulator/opm-parallel/bin/flow --output_dir=test SPE1CASE1.DATA &> /dev/null 
mblatt@boromir:~/src/dune/opm/opm-data/spe1$ ls -l *PRT
-rw-r--r-- 1 mblatt mblatt 537066 Sep  6 14:53 SPE1CASE1.PRT
```

But I agree that it is a bug in opm-simulator.

**Comment by bska** [comment]
> ``` sh
> $ flow --output_dir=test [...]
> ```

Shouldn't this be

``` sh
$ flow output_dir=test [...]
```

i.e., without the double dash in `output_dir`?

**Comment by blattms** [comment]
It is a bug only in opm-simulators if there is a way to tell `EclipseWriter::writeInitAndEgrid` to use a specific directory. Is there?

@bska Yes there should be no dashes. But even with the correct spelling <MODEL>.PRT gets written to in the current directory.

**Comment by atgeirr** [comment]
Not happening for me:

```
atgeirr@galadriel:~/opm/opm-data/spe1$ ~/opm-build-release/opm-simulators-build/bin/flow SPE1CASE1.DATA output_dir=output_test_PRT
```

... results in no PRT file in the current directory, and one in the requested dir with size 536888 bytes.

**Comment by bska** [comment]
@blattms: Do you have commit OPM/opm-output@2e1a92f?

**Comment by blattms** [comment]
I will double check (branch/version/clean build).

**Comment by blattms** [comment]
You guys are right. Only happens in parallel. I used an older opm-simulator version.

**Comment by bska** [comment]
> Only happens in parallel.

Clearly a bug nonetheless.  We should track it.
